---
title: "R Notebook"
output: html_notebook
---

# MS&E 125 Final Project
## Grace, Chanse, Carlene, Katelin, Vlad

```{r}
library(tidyverse)
library(readr)
library(dplyr)
```

```{r}
credit_recovery <- read_csv("Credit Recovery.csv")
credit_recovery <- credit_recovery %>% filter(LEA_STATE == "CA") %>%  na_if(-9) %>% drop_na()
head(credit_recovery,15)
summary(credit_recovery)

d_enrollment <- read_csv("Dual Enrollment.csv")
d_enrollment <- d_enrollment %>% filter(LEA_STATE == "CA") %>%  na_if(-9) %>% drop_na() %>% select(LEAID,LEA_NAME,SCHID, SCH_NAME,COMBOKEY,SCH_DUAL_IND,TOT_DUAL_F,TOT_DUAL_M,SCH_DUALENR_LEP_F,SCH_DUALENR_LEP_M,SCH_DUALENR_IDEA_F,SCH_DUALENR_IDEA_M)

```

```{r}
g_t <- read_csv("Gifted and Talented.csv")
g_t <- g_t %>% filter(LEA_STATE == "CA") %>%  na_if(-9) %>% drop_na() %>% select(LEAID,LEA_NAME,SCHID, SCH_NAME,COMBOKEY,SCH_GT_IND,SCH_GTENR_LEP_M,SCH_GTENR_LEP_F,SCH_GTENR_IDEA_M,SCH_GTENR_IDEA_F)
summary(g_t)
head(g_t,15)
```

```{r}
# load in SAT participation here
SAT_ACT <- read_csv("SAT and ACT.csv")
```


```{r}
IB <- read_csv("International Baccalaureate.csv")
IB <- IB %>% filter(LEA_STATE == "CA") %>%  na_if(-9) %>% drop_na() %>% select(LEAID,LEA_NAME,SCHID, SCH_NAME,COMBOKEY,SCH_IBENR_IND,SCH_IBENR_LEP_M,SCH_IBENR_LEP_F,SCH_IBENR_IDEA_M,SCH_IBENR_IDEA_F)
summary(IB)
head(IB,15)
```

```{r}
#load in school characteristics
characteristics <- read_csv("School Characteristics.csv")
```



```{r}
expenditures <- read_csv("School Expenditures.csv")
expenditures <- expenditures %>% filter(LEA_STATE == "CA") 
head(expenditures)
expenditure_model <- lm(SCH_FTE_AID_WOFED ~ SCH_FTE_SUP_WOFED, 
                  data = expenditures,
                  family = binomial)
summary(expenditure_model)
```

```{r}
college_going = read.delim("collegegoing.txt", na.strings=c("","*", "NA"))

# Chanse's exploration
college_going_1 <- college_going %>% 
  mutate_at(c(13:20), as.numeric) %>%
   filter(!is.na(College.Going.Rate...Total..12.Months.)) %>%
   mutate(CharterSchool = (CharterSchool == "Yes"))

charter_schools <- college_going_1 %>% filter(CharterSchool == TRUE)
noncharter_schools <- college_going_1 %>% filter(CharterSchool == FALSE)
mean(charter_schools$College.Going.Rate...Total..12.Months.)
mean(noncharter_schools$College.Going.Rate...Total..12.Months.)
```

```{r}
# Grace clean up college_going file
college_going <- college_going %>% 
select(AggregateLevel, CountyCode, DistrictCode, SchoolCode, DistrictName, SchoolName, CharterSchool, ReportingCategory, CompleterType, High.School.Completers, Enrolled.In.College...Total..12.Months., College.Going.Rate...Total..12.Months., Enrolled.In.State..12.Months.,Enrolled.Out.of.State..12.Months.) %>% 
  rename(Total_Enrolled_College = Enrolled.In.College...Total..12.Months., Total_College_Going_Rate = College.Going.Rate...Total..12.Months., Total_Enrolled_In_State = Enrolled.In.State..12.Months., Total_Enrolled_Out_State = Enrolled.Out.of.State..12.Months.)

college_going <- na.omit(college_going)
college_going %>% distinct()
college_going <- filter(college_going, CompleterType == 'TA')

#KATELIN CLEANING

#filter only by school name
schools_only = college_going[college_going$AggregateLevel == "S", ]
#filter only by total student count (no breakdown by race/ethnicity)
schools_only = schools_only[schools_only$ReportingCategory == "TA", ]
#filter only by all schools, regardless of charter status
schools_only = schools_only[schools_only$CharterSchool == "All", ]
#delete all columns no longer necessary (all listed above)
schools_only = subset(schools_only, select = -AggregateLevel)
schools_only = subset(schools_only, select = -ReportingCategory)
schools_only = subset(schools_only, select = -CharterSchool)
schools_only = subset(schools_only, select = -CompleterType)



```
#katelin changes 5/31 2:38 PM 
- Added back aggregate level to sort by schools only (eliminating district/state/county designation)
- Added back reporting category to display only totals across races (no breakdown)
- Remove charter school designation to display all (regardless of charter status) - eliminates duplicates

```{r}
# Grace load in graduation rate
grad_rate = read.delim("graduationrate.txt", na.strings=c("","*", "NA"))
grad_rate <- grad_rate %>% 
select(CountyCode, DistrictCode, SchoolCode, DistrictName, SchoolName, CharterSchool, CohortStudents, Regular.HS.Diploma.Graduates..Count.,Regular.HS.Diploma.Graduates..Rate.) %>% rename(Num_Students = CohortStudents, HS_Diploma_Count = Regular.HS.Diploma.Graduates..Count., HS_Diploma_Rate = Regular.HS.Diploma.Graduates..Rate.)
grad_rate <- na.omit(grad_rate)
grad_rate
```

```{r}
# use inner join to merge all the cleaned up data files 
# run regression using all the covariates
```

